Repository dpzhuX/ffpack, pull requests merged in 2023-01, with the labels that each got.

#42 use patch to mock class method
  setup.cfg
  tests/fdr/test_fdr_minerRule.py
Labels: bug

#48 rrm/ use scipy module instead of sp
  src/ffpack/rpm/nataf.py
  src/ffpack/rrm/firstOrderReliabilityMethod.py
  src/ffpack/rrm/firstOrderSecondMoment.py
  tests/rpm/test_rpm_nataf.py
  tests/rrm/test_rrm_firstOrderReliabilityMethod.py
Labels: bug

#51 docs/updated typos in docs
  docs/source/load correction and counting.ipynb
  docs/source/load sequence generator.ipynb
  docs/source/random and probabilistic model.ipynb
Labels: doc

#52 bug/updated deprecated issue
  pyproject.toml
  src/ffpack/rrm/firstOrderReliabilityMethod.py
  src/ffpack/rrm/firstOrderSecondMoment.py
  src/ffpack/utils/generalUtils.py
  tests/utils/test_utils_generalUtils.py
Labels: bug

#54 utils/created miscUtils module
  README.md
  docs/source/module/utils.rst
  src/ffpack/rrm/firstOrderReliabilityMethod.py
  src/ffpack/rrm/firstOrderSecondMoment.py
  src/ffpack/utils/__init__.py
  src/ffpack/utils/generalUtils.py
  src/ffpack/utils/miscUtils.py
  tests/utils/test_utils_generalUtils.py
  tests/utils/test_utils_miscUtils.py
Labels: feature

#56 utils/added Hessian matrix
  README.md
  src/ffpack/lsm/waveSpectra.py
  src/ffpack/rpm/metropolisHastings.py
  src/ffpack/rrm/firstOrderReliabilityMethod.py
  src/ffpack/rrm/firstOrderSecondMoment.py
  src/ffpack/utils/miscUtils.py
  tests/utils/test_utils_miscUtils.py
Labels: feature

#58 utils/add gram schmidt
  src/ffpack/utils/miscUtils.py
  tests/utils/test_utils_miscUtils.py
Labels: feature

#61 rrm/sormBreitung with formCOPT
  README.md
  src/ffpack/rrm/firstOrderReliabilityMethod.py
  src/ffpack/rrm/secondOrderReliabilityMethod.py
  src/ffpack/utils/miscUtils.py
  tests/rrm/test_rrm_firstOrderReliabilityMethod.py
  tests/rrm/test_rrm_secondOrderReliabilityMethod.py
Labels: bug

#66 rrm/added sormHRack
  README.md
  src/ffpack/rrm/secondOrderReliabilityMethod.py
  tests/rrm/test_rrm_secondOrderReliabilityMethod.py
Labels: feature

#68 Lsm/sequence
  README.md
  docs/source/load spectra and matrices.rst
  docs/source/moduleCookbook/lsmSequenceSpectra.ipynb
  src/ffpack/lsm/__init__.py
  src/ffpack/lsm/sequenceSpectra.py
  tests/lsm/test_lsm_sequenceSpectra.py
Labels: feature
